### ISSUE TITLE
Can't sample from a text dataset ? 

### ISSUE THREAD

**Issue by bfleisch** [isee4xai/iSeeDialogManager#30]
The chatbot conversation for the BT Telecom Notes use case (645e3b81cbf032384d5a550e)  is stuck at this point :

![image](https://github.com/isee4xai/iSeeDialogManager/assets/92316278/c34e106a-5871-4ce3-bb0f-e2cb9fbec616)

Error log messages from the container:

```

 -  -  -  PRIORITY State.FAILURE 58c2a7e6-c1a7-4b00-8d65-07c5abd97ea0
 -  -  -  -  EQUAL State.FAILURE 29610e62-e6d1-4115-921a-2aea68824479 {'proceed': True, 'persona': True}
 -  -  -  -  SEQUENCE State.FAILURE 77118415-49ac-4945-85b6-3fc28a657275
 -  -  -  -  -  PERSONA State.FAILURE b2b0a8e8-8f30-4d05-9148-6a40583630a3 I would like to know a more about your knowledge of the system, can you select a user group from below that best describes you?
 -  -  -  -  -  WORLD MODIFIER State.FAILURE 282c5cea-967e-42c9-a7f7-b0a2a613b398 persona True
 -  -  -  PRIORITY State.FAILURE cc1cde22-84d8-42b8-9e77-db668b97567a
 -  -  -  -  EQUAL State.FAILURE 8c5e4c15-4ed8-436e-8fd8-a0a57da2ff3e {'persona': True, 'target': True}
 -  -  -  -  SEQUENCE State.FAILURE 27af3f36-1c8c-47d4-8d64-4ca72d56c6f6
 -  -  -  -  -  TARGET TYPEState.FAILURE 7b5facf8-4929-4be0-888e-c843ad5aed4c sample or upload? selected_target_type
 -  -  -  -  -  PRIORITY State.FAILURE 074c8b7a-a059-4397-9e7d-e02dd340e746
 -  -  -  -  -  -  SEQUENCE State.FAILURE 6f2563f7-56fb-4cc0-a862-5861c32b577d
 -  -  -  -  -  -  -  EQUAL VALUE State.FAILURE 1e5a8e20-0dc2-4947-8d12-79942deadff5 {'selected_target_type': 'SAMPLE'}
 -  -  -  -  -  -  -  SEQUENCE State.FAILURE 3d2d4049-3ce5-43d7-a913-373fdc635c9b
 -  -  -  -  -  -  -  -  TARGET State.FAILURE 7510bb2a-b9d4-4381-81f9-4aa0219944f3 Here is your loan application and the AI system outcome selected_target
 -  -  -  -  -  -  -  -  WORLD MODIFIER State.FAILURE 53b8dd1b-cd1d-45c1-8a1c-29e63cfd734e target True
 -  -  -  -  -  -  SEQUENCE State.FAILURE a03c050e-8838-4e70-8508-aa7fd0458421
 -  -  -  -  -  -  -  EQUAL VALUE State.FAILURE 2f711f49-5c20-4be9-bed7-7eb4cd93e445 {'selected_target_type': 'UPLOAD'}
 -  -  -  -  -  -  -  SEQUENCE State.FAILURE 85fa8121-8606-4c68-96bc-d3d2447dbad3
 -  -  -  -  -  -  -  -  TARGET State.FAILURE 3067047b-fe76-40f7-8203-db6ed76ef9e8 Please upload your instance selected_target
 -  -  -  -  -  -  -  -  WORLD MODIFIER State.FAILURE 8cca4628-a94b-4de7-800f-7673c5113f7a target True
 -  -  -  REP TILL SUCC State.FAILURE cd3a3eb9-3443-4558-82cb-330bf61a14a4
 -  -  -  -  SEQUENCE State.FAILURE 8c4fdfd8-5b3c-4f78-8abc-170195edf509
 -  -  -  -  -  PRIORITY State.FAILURE 8101f41a-fe19-4c9f-84ad-7495608e0098
 -  -  -  -  -  -  EQUAL State.FAILURE fb91f20a-d142-42a0-92c7-25bf65822ec0 {'need': True, 'persona': True, 'target': True}
 -  -  -  -  -  -  SEQUENCE State.FAILURE 09cded4c-6464-4c05-b97c-daa22f2bfea9
 -  -  -  -  -  -  -  NEED QUESTION State.FAILURE cb985c59-1145-4ec1-83f9-d1eb92a19a65 Please select a question below to indicate your explanation need selected_need []
 -  -  -  -  -  -  -  WORLD MODIFIER State.FAILURE 6825f4fa-e397-45ef-a263-b6488802100f need True
 -  -  -  -  -  EXPLANATION STRATEGY State.FAILURE 6f249eee-b61b-4c11-82a4-ce95d3390343
 -  -  SEQUENCE State.FAILURE 1633b6e6-c578-4347-9649-6c6de19d6bf8
 -  -  -  EQUAL State.FAILURE 18704e1a-d968-471b-ba78-9b1ac46fcb2b {'evaluation': False}
 -  -  -  PRIORITY State.FAILURE c50f7103-0678-449d-af52-06485e92da7f
 -  -  -  -  INVERTER State.FAILURE aede7479-a7c3-4f4e-8d0c-6714bcf47c90
 -  -  -  -  -  CONFIRM State.FAILURE 1582ff0f-11de-47d4-a639-d6b34c6ec2cd Would you like to answer a questionnaire to evaluate your experience with iSee? evaluate_proceed
 -  -  -  -  SEQUENCE State.FAILURE e507a989-9f1c-4c0b-8358-cd94aaf229f0
 -  -  -  -  -  EVALUATION STRATEGY State.FAILURE b248351d-fd85-42a4-88d4-b1421e7ee72f
 -  -  -  -  -  WORLD MODIFIER State.FAILURE 25aa331e-dcf7-4764-8885-cf0079628f0d evaluation True
 -  -  SEQUENCE State.FAILURE de36a4b7-e0b6-46b1-9ba0-9d391062060b
 -  -  -  EQUAL State.FAILURE 0a5747a4-f6dd-4aed-ab7f-381b2df1c8ee {'complete': False}
 -  -  -  GREETER State.FAILURE 9eeb25f3-0cf4-424a-bf62-2e440f2af194 complete_response
 -  -  -  WORLD MODIFIER State.FAILURE 7384720c-4da6-4428-a7ff-ccecc4ac7666 complete True
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 325, in app
    await dependant.call(**values)
  File "/app/main.py", line 83, in websocket_endpoint
    await manager.start(client_id, init_data)
  File "/app/main.py", line 67, in start
    await self.coordinators[client_id].start()
  File "/app/business/coordinator.py", line 33, in start
    await self.bt.run()
  File "/app/business/bt/bt.py", line 14, in run
    await self.tree.root.tick()
  File "/app/business/bt/nodes/node.py", line 40, in tick
    await self.children[0].tick()
  File "/app/business/bt/nodes/composite.py", line 44, in tick
    if (await child.tick() == State.FAILURE):
  File "/app/business/bt/nodes/composite.py", line 44, in tick
    if (await child.tick() == State.FAILURE):
  File "/app/business/bt/nodes/composite.py", line 17, in tick
    if (await child.tick() == State.SUCCESS):
  File "/app/business/bt/nodes/composite.py", line 44, in tick
    if (await child.tick() == State.FAILURE):
  File "/app/business/bt/nodes/composite.py", line 17, in tick
    if (await child.tick() == State.SUCCESS):
  File "/app/business/bt/nodes/composite.py", line 44, in tick
    if (await child.tick() == State.FAILURE):
  File "/app/business/bt/nodes/composite.py", line 44, in tick
    if (await child.tick() == State.FAILURE):
  File "/app/business/bt/nodes/action.py", line 435, in tick
    instance =  html.table(instance_json)
  File "/app/business/bt/nodes/html_format.py", line 14, in table
    _df = pd.json_normalize(_json)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/json/_normalize.py", line 445, in json_normalize
    raise NotImplementedError
NotImplementedError
INFO:     connection closed
```

**Comment by anjanaw** [comment]
Hello Bruno, Please see the screenshot.
Sampling is fixed and check the AI model prediction is as expected.

I have disabled upload for _text_ dataset type for now. So there will not be an option to select either sample or upload.

<img width="959" alt="Screenshot 2024-02-02 at 15 44 55" src="https://github.com/isee4xai/iSeeDialogManager/assets/233262/58767711-a54e-4380-ad65-0b3176602960">
